/*
📘 GenAI Playlist – LangChain
Lecture-4 | Video-6 | CampusX
Topic: Prompt Engineering (Text-Based Prompts & Chat Prompts)

==================================================
🔹 What are Prompts?
==================================================
Prompts are the input instructions or queries
that we give to an LLM (Large Language Model)
to guide its output.

In simple words:
Prompt decides how the model should think
and what kind of response it should generate.

LLM models heavily depend on prompts.
Same model + different prompt = different output.

==================================================
🔹 Why Prompts are Important?
==================================================
- Poor prompt  → vague / incorrect response
- Good prompt  → accurate, structured response
- Prompt quality directly affects output quality

==================================================
🔹 Types of Prompts
==================================================

1️⃣ Static Prompts
------------------
- Prompt is fixed
- User writes the complete prompt

Problems with Static Prompts:
- User gets too much control
- Prompt structure can break
- Output can be unpredictable or unsafe
- Not ideal for production systems

--------------------------------------------------

2️⃣ Dynamic Prompts (Recommended ✅)
----------------------------------
- Prompt template is pre-defined
- User gives only limited inputs
- Core prompt structure is controlled
  by the developer

This is the ideal and real-world approach.

==================================================
🔹 Dynamic Prompt Concept
==================================================
Instead of letting user write the full prompt,
we ask for only specific inputs.

User provides:
- Topic
- Explanation style (code-heavy / text-heavy)
- Output format or difficulty level

These values are injected into
a predefined prompt template.

==================================================
🔹 Example: Dynamic Prompt Flow
==================================================
User Inputs:
- Topic: Binary Search
- Explanation Type: Code-heavy

Internal Prompt Template:
"Explain {topic} in a {style} manner
with clear examples."

==================================================
🔹 Common Doubt ❓
==================================================
"Hum f-string bhi toh use kar sakte hain,
phir PromptTemplate kyu use karein?"

Yes, f-strings CAN be used,
but PromptTemplate is preferred for 3 reasons.

==================================================
🔹 Why PromptTemplate is Better than f-strings?
==================================================

1️⃣ Validation
--------------
- PromptTemplate validates required variables
- Prevents missing or incorrect inputs
- f-strings provide NO validation

2️⃣ Reusability
---------------
- Same template reused across multiple LLM calls
- Easy to maintain and update
- f-strings are tightly coupled to code blocks

3️⃣ LangChain Ecosystem Integration
-----------------------------------
- Works seamlessly with:
  - LLMChain
  - Runnables
  - OutputParsers
  - Memory
- f-strings are plain Python strings
  (no ecosystem support)

==================================================
🔹 Moving to Chatbots (Conversation Mode)
==================================================
Now we build a chatbot where conversation happens
in a multi-turn manner.

For this, we must send:
- Full conversation history
- Not just the latest user input

==================================================
🔹 Message Types in LangChain
==================================================
LangChain provides 3 message types:

1️⃣ SystemMessage
-----------------
- Defines system behavior / role
- Example:
  "You are a helpful AI assistant"

2️⃣ HumanMessage
----------------
- Message sent by the user

3️⃣ AIMessage
-------------
- Message generated by the model

==================================================
🔹 Chat Prompt Templates – Big Picture
==================================================

                           Model
                            |
                         invoke()
                            |
              --------------------------------
              |                              |
        Single Message                List of Messages
     (Single-turn queries)         (Multi-turn conversation)
              |                              |
        ----------------              ---------------------
        |              |              |                   |
   Static Message   Dynamic Message   Static Messages   Dynamic Messages
                     (PromptTemplate) (SystemMessage,   (Context-aware
                                      HumanMessage,     user messages)
                                      AIMessage)

==================================================
🔹 Explanation
==================================================
- Single Message:
  - Used for standalone questions
  - Can be static or created dynamically
    using PromptTemplate

- List of Messages:
  - Used for chat-based / conversational flows
  - Maintains memory using message history

- invoke():
  - Entry point of the model
  - Accepts either:
    - a single prompt
    - OR a list of messages

==================================================
🔹 PromptTemplate vs ChatPromptTemplate
==================================================
- PromptTemplate:
  - Used mainly for single-message prompts
  - Focused on text generation

- ChatPromptTemplate:
  - Used when working with a list of messages
  - Helps make SystemMessage dynamic
  - Ideal for chatbot / conversation-based apps

==================================================
🔹 Key Takeaway 💡
==================================================
Users should NOT write prompts.
Users should FILL prompts.

Dynamic prompts + chat message history
are preferred in LangChain and
real-world GenAI applications.
*/
